DOMAIN-SUFFIX,aaplimg.com,AppleServers
DOMAIN-SUFFIX,apple-cloudkit.com,AppleServers
DOMAIN-SUFFIX,apple-dns.net,AppleServers
DOMAIN-SUFFIX,apple-mapkit.com,AppleServers
DOMAIN-SUFFIX,apple.co,AppleServers
DOMAIN-SUFFIX,apple.com,AppleServers
DOMAIN-SUFFIX,apple.news,AppleServers
DOMAIN-SUFFIX,appsto.re,AppleServers
DOMAIN-SUFFIX,appstore.com,AppleServers
DOMAIN-SUFFIX,cdn-apple.com,AppleServers
DOMAIN-SUFFIX,icloud-content.com,AppleServers
DOMAIN-SUFFIX,icloud.com,AppleServers
DOMAIN-SUFFIX,itunes.com,AppleServers
DOMAIN-SUFFIX,me.com,AppleServers
DOMAIN-SUFFIX,organicfruitapps.com,AppleServers
DOMAIN-SUFFIX,push-apple.com.akadns.net,AppleServers