DOMAIN-SUFFIX,local,Lan
IP-CIDR,10.0.0.0/8,Lan,no-resolve
IP-CIDR,100.64.0.0/10,Lan,no-resolve
IP-CIDR,127.0.0.0/8,Lan,no-resolve
IP-CIDR,172.16.0.0/12,Lan,no-resolve
IP-CIDR,192.168.0.0/16,Lan,no-resolve
IP-CIDR,224.0.0.0/4,Lan,no-resolve
IP-CIDR,fe80::/10,Lan,no-resolve